apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: health-samurai-web
build:
  artifacts:
    - image: health-samurai-web
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - k8s/overlays/dev/**/*.yaml
portForward:
  - resourceType: deployment
    resourceName: dev-health-samurai-web
    namespace: health-samurai-dev
    port: 4444
    localPort: 4444
profiles:
  - name: prod
    deploy:
      kubectl:
        manifests:
          - k8s/overlays/prod/**/*.yaml
    portForward:
      - resourceType: deployment
        resourceName: prod-health-samurai-web
        namespace: health-samurai-prod
        port: 4444
        localPort: 4444
